format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    materials:
      git-2058dd3:
        git: https://github.com/iteration-1/expense--terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec: {command: terraform,  arguments:["init", "-backend-config=env-dev/state.tfvars"], run_if: passed}
                - exec: {command: terraform,  arguments: [ "destroy", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed }

